# Generated by Django 5.2.4 on 2025-07-11 05:36

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=store.models.get_file_path)),
                ('description', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0=default,1Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1Hidden')),
                ('meta_title', models.CharField(max_length=50)),
                ('meta_keyword', models.CharField(max_length=50)),
                ('meta_description', models.CharField(max_length=50)),
            ],
        ),
    ]
